services:
  - type: web
    name: ledybot-webhook
    env: python
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn ledybot_webhook:app --host=0.0.0.0 --port=$PORT"
    pythonVersion: 3.11.6
